import fs from "node:fs";
import path from "node:path";

/** Slugs that are rendered natively in-app (not via the iframe artifact viewer). */
export const NATIVE_FTD_SLUGS = new Set<string>([
  "frontier-threat-defense-kill-chain",
  "frontier-threat-defense-program-strategy",
]);

export function isNativeFtd(slug: string): boolean {
  return NATIVE_FTD_SLUGS.has(slug);
}

export interface FtdAsset {
  html: string;
  css: string;
  js: string;
  cite: string;
}

/**
 * Read the pre-built native FTD assets (generated by scripts/build-ftd-native.mjs).
 * Runs at build time in the server component during static export.
 */
export function getFtdAsset(slug: string): FtdAsset | null {
  if (!isNativeFtd(slug)) return null;
  const dir = path.join(process.cwd(), "src", "content", "ftd");
  const read = (ext: string) => fs.readFileSync(path.join(dir, `${slug}.${ext}`), "utf8");
  try {
    return {
      html: read("html"),
      css: read("css"),
      js: read("js"),
      cite: read("cite.json"),
    };
  } catch {
    return null;
  }
}
