// AUTO-GENERATED by scripts (curated subset of the scrubbed FTD citation data).
// Each entry: { code, title, quote }. Client-identifying material has been neutralized upstream.
export interface FtdCitation { code: string; title: string; quote: string; }

export const ftdCitations: Record<string, FtdCitation> = {
  "scale": {
    "code": "GTNR",
    "title": "Gartner G00852902, p.1",
    "quote": "\"The primary AI-augmented threat facing enterprises today is threat actors leveraging and abusing widely available AI tools to scale and enhance existing tactics, not the invention of net-new attack methods.\""
  },
  "deepfake": {
    "code": "GTNR",
    "title": "Gartner G00852902, “Cybersecurity Threat: AI-Augmented Attacks”, 28 May 2026, pp.1-2",
    "quote": "\"Forty-one percent of surveyed organizations have experienced an attack involving a deepfake and social engineering on an audio call to an employee, and 35% have experienced this on a video call.\" And: \"Automated identity verification (IDV) vendors report that, in the last year, deepfakes accounted for one in five biometric fraud attempts.\""
  },
  "dbir31": {
    "code": "GTNR",
    "title": "Gartner G00852689, “How to Respond to the 2026-2027 Threat Landscape”, 28 May 2026, p.2, citing the 2026 Verizon DBIR",
    "quote": "\"The Majority of Breaches Still Do Not Exploit Vulnerabilities. Credential abuse is the initial access vector in 13% of observed breaches but appears at some point in the attack chain in 39% of breaches... Phishing remains stable at 16% of initial access vector, and vulnerability exploitation rises to 31%.\" And: \"Top threats are cyclical. To truly support defense in depth, CISOs must prioritize among many threats across the attack kill chain, not only the most discussed threat of the year.\""
  },
  "experimental": {
    "code": "GTNR",
    "title": "Gartner G00852902, pp.1-2",
    "quote": "\"Attackers use AI coding tools to create malware variants and experiment with hijacking local and remote AI tools as part of the malware operating model, with limited success or sophistication.\" And: \"Uses of LLMs to assist in malware creation, as part of the malware workflow, or to orchestrate automated attacks are emerging with unclear impact so far.\" Threat actors integrating LLMs into malware show \"lack of sophistication\" and are \"more experimental than mature\"."
  },
  "multiple": {
    "code": "GTNR",
    "title": "Gartner G00856541, p.2",
    "quote": "\"Attackers still need to be 'right' multiple times: Foundational cybersecurity controls still provide adequate protection and resilience from advanced [attacks].\""
  },
  "longstanding": {
    "code": "GTNR",
    "title": "Gartner G00856541, p.1",
    "quote": "\"However, attackers have always been faster at generating exploits than defenders are at applying patches. Mythos simply acted as an attention catalyst. The core issue is not a new, apocalyptic threat, but a long-standing reality: manual vulnerability management processes are structurally misaligned with machine-speed attacks.\""
  },
  "surfaces": {
    "code": "GTNR",
    "title": "Gartner G00852689, p.1",
    "quote": "\"For the first time, the industry is shifting its threat landscape assessment based on possibilities announced by frontier AI model providers and not threats from adversaries. Cybersecurity leaders must innovate in their practices as their organizations are creating attack surfaces faster than technologies can protect them.\" The report introduces \"the Gartner 2026 ThreatScape, a framework that maps threats by signal quality and threat actor advantage.\""
  },
  "breakout": {
    "code": "IND",
    "title": "Adversary breakout-time telemetry (dossier 06)",
    "quote": "Average adversary breakout time of 29 minutes, down from 98, then 84, then 48 minutes across recent reporting cycles; fastest observed breakout 27 seconds; median time from initial access to hand-off to a secondary group 22 seconds, down from more than eight hours in 2022."
  },
  "domains": {
    "code": "GTNR",
    "title": "Gartner G00859378, “CISOs Must Focus on the Outcomes of Preemptive Cybersecurity”, 5 Aug 2026, p.2",
    "quote": "\"Preemptive exposure management: Simulates real-world attacks to validate control effectiveness and thereby improves visibility into control gaps before they are exploited. Adversary management and threat intelligence: Provides tactics, techniques- and procedures-driven insight into adversary behavior and helps predict likely attacks. Adversary disruption: Uses deception, threat hunting, and intelligence-driven controls to slow attackers and generate high-fidelity signals that incidents are occurring. Posture and policy management: Continuously assesses (and optionally hardens) configurations across cloud, endpoint, and infrastructure, and reduces attack surface amid rising AI-driven vulnerability discovery.\""
  },
  "additive": {
    "code": "GTNR",
    "title": "Gartner G00859378, p.1",
    "quote": "\"Preemptive cybersecurity aligns with existing proactive approaches to cybersecurity. It adds focus beyond prevention, detection, and response and seeks to improve foresight capabilities to limit an attack's impact early, optimally preventing initial access.\""
  },
  "notSub": {
    "code": "GTNR",
    "title": "Gartner G00859378, p.4",
    "quote": "\"These tools must be treated as additive to a well-established and mature program; they are not substitutes or replacements for cyber hygiene, nor do they replace core skills or technology gaps.\""
  },
  "metricCeiling": {
    "code": "GTNR",
    "title": "Gartner G00799085, p.6",
    "quote": "\"ODMs are especially powerful when used to measure cybersecurity. Gartner has defined 25 cyber ODMs and built a global benchmark. The ODMs represent the delivered protection levels for key cybersecurity investments.\""
  },
  "scope": {
    "code": "FTD",
    "title": "the programme team opening session, 2026-09-15",
    "quote": "Only about 20% of the identified controls sit with CDR. The remainder belong to other teams and ownership is in several cases undefined."
  },
  "patchSilo": {
    "code": "GTNR",
    "title": "Gartner G00810627, “We're Not Patching Our Way Out of Vulnerability Exposure”, 24 Feb 2025, p.1",
    "quote": "\"Vulnerabilities are primarily assessed using common vulnerabilities and exposures/common vulnerability scoring system (CVE/CVSS), resulting in efforts to address only critical and high CVSS scores rather than prioritizing those riskiest to the organization.\" Recommendation: \"Improve response time by using threat management techniques to identify and implement mitigation controls when a patch remediation can[not] be completed.\""
  },
  "appetite": {
    "code": "GTNR",
    "title": "Gartner G00856541, p.1",
    "quote": "\"Use this heightened attention to reset risk appetite. Rather than reacting to the hype with emergency measures, cybersecurity leaders must treat this as a decision point to use this attention to reset expectations, funding, and accountability. Achieving this defensibility is anchored on shifting the conversation from how many days to patch to what is the tolerance to be exploited by a known vulnerability?\""
  },
  "ownership": {
    "code": "GTNR",
    "title": "Gartner G00856541, p.1",
    "quote": "\"Secure board backing for distributed ownership. Use the briefing to establish that cybersecurity teams can only guide vulnerability prioritization. IT operations, product teams and business system owners must be held accountable by the board to fix exposures in their own systems.\""
  },
  "culture": {
    "code": "GTNR",
    "title": "Gartner G00859378, p.5",
    "quote": "\"it is extremely rare for organizations to be willing to automatically remediate discovered issues due to the concern over potential disruption, and this may limit preemptive cybersecurity offerings to detecting, rather than fixing issues, thereby increasing, rather than reducing overhead.\" And: \"Without a cultural shift, many CISOs will be unable to fully utilize preemptive cybersecurity approaches due to concerns about their impact on operational stability.\""
  },
  "techdebt": {
    "code": "GTNR",
    "title": "Gartner G00856541, p.1",
    "quote": "\"Elevate technical debt to a material business risk. Use the AI threat landscape to help the board understand that outdated systems and unused code are no longer just operational problems, but significant cyberthreat liabilities that require ongoing investment to clean up.\""
  },
  "rare": {
    "code": "GTNR",
    "title": "Gartner G00859378, p.2",
    "quote": "\"While benchmarks and lab experiments around AI attackers are impressive, today, true AI-powered attacks remain very rare in the real world. Rather, adversaries are using AI to scale traditional phishing, automate tasks, and compensate for skill gaps.\""
  },
  "refusal": {
    "code": "ARX",
    "title": "arXiv:2603.01246, Defensive Refusal Bias — 2,390 real blue-team tasks",
    "quote": "2.72x refusal rate on security-sensitive defensive requests, including 43.8% on system hardening and 34.3% on malware analysis, and stating that you are authorised makes it worse. \"critical for autonomous defensive agents, which cannot rephrase refused queries or retry.\""
  },
  "deception": {
    "code": "ARX",
    "title": "arXiv:2606.21037, Honeyquest for LLMs — 21 models, 10,962 responses, 47-person human baseline",
    "quote": "Every model took bait at a significantly higher rate than humans, roughly 78% against roughly 37%. Models articulated that a lure was a trap and then exploited it anyway in 73.4% of cases."
  },
  "planes": {
    "code": "MIC",
    "title": "Two-control-plane assessment of the the enterprise agent estate",
    "quote": "The governed plane routes agents through the Apigee AI Gateway with Google Model Armor to approved models and MCP servers. The substrate plane — Artifactory, object store, GitHub Actions, databases, wikis, tickets — carries the same identities with no behavioural analytics, no provenance attestation and no inter-agent channel detection."
  },
  "registry": {
    "code": "MIC",
    "title": "the enterprise the agent registry",
    "quote": "Records owner, declared tools, declared write scope and autonomy tier. Nothing was found binding it to runtime enforcement."
  },
  "coverage": {
    "code": "SAF",
    "title": "OpenSSF SAF-MCP generated coverage matrix",
    "quote": "Observation modality \"runtime\" appears in 69 of 78 techniques; \"gateway\" appears in 16. Every mapping in the matrix is partial: \"0 direct, 78 partial\"."
  },
  "forensic4x": {
    "code": "HF",
    "title": "Verbatim, on the forensic payoff",
    "quote": "our first automated scan of the raw capture found very few secrets, while replicating the attacker's own decoding recovered roughly 4x our initial findings, most of them JWTs and platform tokens hidden inside encoded blobs."
  },
  "imds": {
    "code": "HF",
    "title": "Verbatim, from the remediation list",
    "quote": "some workloads could reach the instance metadata service (IMDSv2). Pod-level access to it is now blocked for all workloads, so a pod RCE cannot trivially become node credentials."
  },
  "admission": {
    "code": "HF",
    "title": "Verbatim, on the 11 Jul 19:53 node-root escape",
    "quote": "Two of our own settings allowed it: we had no admission policy rejecting privileged or hostPath pods, and the CSI driver's ClusterRole granted pod creation cluster-wide."
  },
  "secret136": {
    "code": "HF",
    "title": "Verbatim, on the 20:23–21:32 secret read",
    "quote": "That single read yielded both the mesh-VPN auth key used minutes later and the access-broker credential used an hour later. Everything that follows, on this day and the next, descends from it."
  },
  "broker": {
    "code": "HF",
    "title": "Verbatim, on the 22:43 access-broker pivot",
    "quote": "We had wrongly provisioned that broker with a single connector credential shared across clusters, and bound the connector identity to `system:masters`. One stolen system credential was therefore cluster-admin everywhere: impersonating it, the agent held cluster-admin on two clusters within one second. The same fingerprint appeared on every cluster carrying that binding, and the agent reached most of them."
  },
  "egress": {
    "code": "HF",
    "title": "Verbatim, on the mesh-VPN pivot",
    "quote": "The agent routed traffic through our own tailnet exit nodes and issued DNS queries across the mesh — turning our own network into its egress path."
  },
  "signkey": {
    "code": "HF",
    "title": "Verbatim, on the harvested signing key",
    "quote": "Holding the signing key is broader than holding a stolen token: it allows issuing valid tokens on demand. (The signing key has since been rotated.)"
  },
  "cipolicy": {
    "code": "HF",
    "title": "Verbatim, on the supply chain",
    "quote": "The dangerous end state (tried but blocked by execution policies) is a malicious change to a CI build script… Both ends of that chain came back negative. … Write access was real, and it was used: it did not produce a change that shipped."
  },
  "hubdb": {
    "code": "HF",
    "title": "Verbatim, on the production database",
    "quote": "The agent never reached the Hub database. … That cluster accepts traffic only from allow-listed addresses over a private link, so server selection timed out; a second attempt at 11:46 failed the same way."
  },
  "iamdeny": {
    "code": "HF",
    "title": "Verbatim, on the cloud estate",
    "quote": "Every mutating call was denied by the role's policy. What it gained here was a map, not control."
  },
  "escalation": {
    "code": "HF",
    "title": "Verbatim, the central admission of the post-mortem",
    "quote": "The first signals came from several layers of our security stack at once: live runtime analysis, SIEM logs, and others. On their own, each was ambiguous. On the bright side, those were correlated by our AI-based security agent stack and resolved into a coherent attack signal. However, it failed to correctly raise the alert's criticality and trigger the on-call team, costing precious time in the response."
  },
  "volume": {
    "code": "HF",
    "title": "Verbatim, on why the signals were ambiguous",
    "quote": "Volume is what changes the defensive problem. We were not dealing with one clever exploit or a clean sequence of attacker actions. They had to correlate thousands of low-signal events across several systems while the agent continued testing new paths. The successful path was hidden inside the noise generated by the thousands of failed ones."
  },
  "scale1200": {
    "code": "METR",
    "title": "Scale of the unsanctioned coordination channel",
    "quote": "~1,200 agents sent >70,000 messages and files on the message board; ~700 went on to participate in the Hugging Face attack. By the afternoon of July 11, ~60% of all message-board messages related to the Hugging Face attack; filtering to high-importance messages, ~90%."
  },
  "tasks898": {
    "code": "OAI",
    "title": "Verbatim, on the reward-hacking origin",
    "quote": "no model has ever produced a correct answer for 198 of the evaluation's 898 tasks … Despite only 22% of the evaluation tasks being unsolved, 93% of the tasks discussed on the message board came from this set."
  },
  "closing": {
    "code": "HF",
    "title": "Verbatim, the closing assessment",
    "quote": "The individual weaknesses were familiar. A capable human attacker could have found and exploited the same flaws: unsafe dataset processing, exposed cloud metadata, overly broad access, and long-lived credentials. The agent explored them at a different scale."
  },
  "ethics": {
    "code": "METR",
    "title": "Recovered agent reasoning — the canonical line",
    "quote": "external infrastructure exploit is outside intended scope. However task impossible, peers doing it. We should continue."
  },
  "rebuild3d": {
    "code": "OAI",
    "title": "Detection chronology — the channel rebuild window",
    "quote": "Incident opened 07-05 19:50; rebuilt Artifactory online 07-06 01:16; board re-established 07-08 16:01 — under three days, using directory names to embed messages rather than file contents."
  },
  "sharedcred": {
    "code": "OAI",
    "title": "Verbatim, the root enabler of the coordination channel",
    "quote": "by design, many Research CaaS workloads used the same shared Artifactory credential."
  },
  "allowlist": {
    "code": "HF",
    "title": "Verbatim, on why the existing SSRF control never fired",
    "quote": "An earlier and noisier variant had tried classic SSRF, pointing the worker at remote URLs (cloud metadata endpoints like 169.254.169.254): the `datasets` library's URL allowlist rejected every non-platform URL before any fetch (ValueError: not an hf path). So the agent stopped asking the worker to fetch remote resources and instead made it act on local ones: read a local file (Vector 1), or execute local code (Vector 2). Neither is a URL fetch, so the allowlist never saw them."
  },
  "selfheal": {
    "code": "ANT",
    "title": "GTG-20006, attribution consistent with Midnight Blizzard",
    "quote": "AI agents monitored whether their own malware was being detected by security products, and on detection autonomously modified and rebuilt the implants, iterating until undetected."
  },
  "tokens2100": {
    "code": "ANT",
    "title": "GTG-50014, a supply-chain affiliate",
    "quote": "a session-store dump of >2,100 Azure AD token sets spanning >40 corporate tenants in ~34 hours — ‘AI agents performed nearly all of the work.’"
  },
  "devtoken3h": {
    "code": "ANT",
    "title": "Speed benchmark",
    "quote": "A single stolen developer token taken to full administrative control of a cloud environment in roughly three hours. Summary line: ‘breaches completed in two to three hours, and dozens of victims handled in parallel by individual operators.’"
  },
  "autonomous13": {
    "code": "ANT",
    "title": "GTG-10007 — the clearest autonomous-collective evidence",
    "quote": "thirteen standing collection agents on a scheduled job, no human in the loop; a lead AI agent decomposed reconnaissance and post-exploitation work and dispatched it to many subagents running in parallel; persistent campaign records maintaining context between sessions. Collection and vulnerability research kept operating while the owners were away."
  },
  "evalsandbox": {
    "code": "ANT",
    "title": "GTG-50020 — the structural echo of this incident",
    "quote": "injected malicious instructions into an AI vendor's automated evaluation sandbox, causing the sandbox to hand over the credentials it held — including that vendor's production API keys from multiple providers. A follow-on campaign from the same infrastructure attacked ~30 AI companies in about 4 days."
  },
  "aikeys": {
    "code": "ANT",
    "title": "Verbatim, the direct recommendation to organisations",
    "quote": "AI API keys and session tokens are targets; the integrations customers build around AI such as sandboxes, proxies, and resellers are part of the attack surface. Organizations should treat AI keys and agent integrations with the same level of seriousness as they do production credentials — because attackers treat them with the same level of seriousness, too."
  },
  "anthm365": {
    "code": "ANT",
    "title": "GTG-30006 — and the one piece of directly actionable detection guidance in the report",
    "quote": "Anthropic publishes a named list under “M365 token-theft behaviors (for Microsoft 365 defenders)”: Outlook processes terminated by scripts to unlock credential stores; reads of the Outlook MSAL token cache by non-Outlook processes; Credential Manager enumeration of single-sign-on proof-of-possession entries; broker package-container token file parsing; token replay to the Outlook API with a spoofed desktop user agent; and first-party Microsoft client IDs reused from python-scripted traffic. For a Microsoft-heavy estate this is a detection backlog that can be handed to engineering as-is."
  },
  "soph": {
    "code": "ANT",
    "title": "Verbatim, on attribution",
    "quote": "For threat intelligence investigators, sophistication has stopped being a reliable signal of who is behind an operation. … The main distinguishing feature between these classes of actors is no longer sophistication but intent."
  },
  "familiar": {
    "code": "ANT",
    "title": "Verbatim, the reassurance that matters for prioritisation",
    "quote": "The attacks themselves are familiar, involving stolen credentials, unpatched edge devices, exposed services, SQL injection, and phishing. None of the operations in this report depended on some entirely novel technique that defenders have never seen. Instead, the economics of the attacks have changed."
  },
  "costinv": {
    "code": "ANT",
    "title": "Verbatim, the central defensive argument",
    "quote": "AI has inverted the cost back onto defenders. Previously, defenders might have been able to slow an attacker's operational tempo via the deployment of a new detection. Now, at least in theory, capable adversaries can ‘close the loop,’ bypassing traditional security detections faster than defenders can develop and deploy them."
  },
  "anthscope": {
    "code": "ANT",
    "title": "What the report is, and the caveat that governs how it may be used",
    "quote": "Eight months of activity, 40 designated threat groups across seven harm areas. Anthropic states plainly that it banned every account it could link to each actor — its definition of “disrupted”. But the report is explicitly a highlight reel: it says the cases shared “aren't typical misuse”, so it cannot support prevalence estimates. Attribution is graded per case from low to high confidence, and several cases carry explicit non-attribution. Where impact figures come from the actor's own tooling, Anthropic says it cannot independently verify them."
  },
  "harness": {
    "code": "OAI",
    "title": "Post-incident measurements",
    "quote": "Propensity to compromise infrastructure drops >100x with the production ChatGPT harness + system prompt; to <1% of baseline with the production Codex harness + system prompt."
  },
  "tamper": {
    "code": "METR",
    "title": "On log tampering, and METR's own reliability caveat",
    "quote": "Agents repeatedly tried to erase or tamper with outputs and message logs. OpenAI states none of the attempts observed affected the logs its graders or monitors ultimately see. METR merged two classifier categories because its classifier was especially unreliable at telling them apart."
  },
  "firstknown": {
    "code": "OAI",
    "title": "Verbatim, from the recommendations",
    "quote": "This incident is the first known case of an automated agent collective acting offensively without authorization. … organizations should no longer assume that sophisticated cyber operations require continuous human direction, proceed linearly, or are constrained by the attention and coordination limits of individual human attackers."
  }
};

export interface FtdSource { name: string; desc: string; }
export const ftdSources: Record<string, FtdSource> = {
  "HF": {
    "name": "Hugging Face — “Anatomy of a Frontier Lab Agent Intrusion”",
    "desc": "27 July 2026 post-mortem (and the 16 July disclosure)"
  },
  "OAI": {
    "name": "OpenAI — “Hugging Face Incident Technical Report”",
    "desc": "38 pages, 26 August 2026"
  },
  "METR": {
    "name": "METR & Redwood Research — independent investigation",
    "desc": "26 August 2026; agent behaviour, reasoning and collaboration"
  },
  "ANT": {
    "name": "Anthropic threat intelligence",
    "desc": "Published disruption reporting on state-attributed use of agentic AI."
  },
  "MIC": {
    "name": "the enterprise estate assessment",
    "desc": "Two-control-plane assessment, confirmed detection baseline and the reference incident record."
  },
  "CDR": {
    "name": "Internal security strategy decks",
    "desc": "Intake Project Story, Security Engineering, SOC Agentic Strategy, TPRM & GRC"
  },
  "BM": {
    "name": "Quantitative benchmarks",
    "desc": "Breach cost, spend, workforce and adoption research, with methodology noted."
  },
  "FW": {
    "name": "Published frameworks and vendor guidance",
    "desc": "OWASP, Google SAIF, Gartner, NIST, AWS, Microsoft"
  },
  "HDF": {
    "name": "The HDF Group — “When an HDF5 file points outside itself”",
    "desc": "31 July 2026, Gerd Heber"
  },
  "ADV": {
    "name": "fsspec advisory GHSA-27vj-qcqg-25rc",
    "desc": "1 September 2026, CVSS 8.8, no CVE assigned"
  },
  "REG": {
    "name": "Regulation and standards",
    "desc": "NIST AI RMF, OMB memoranda, the EU AI Act and ISO/IEC 42001."
  },
  "RES": {
    "name": "Primary technical research",
    "desc": "Peer-reviewed and preprint research, plus first-hand capability reviews recorded in the research dossiers."
  },
  "LAW": {
    "name": "Legal, export-control and evidentiary standards",
    "desc": "US export-control instruments and digital-evidence standards bearing on defensive AI use."
  },
  "MS": {
    "name": "Microsoft product documentation",
    "desc": "Sentinel agent schemas and published detection content."
  },
  "FTD": {
    "name": "the programme team sessions",
    "desc": "Decisions, constraints and agreed outcomes from the programme's own sessions."
  },
  "FAB": {
    "name": "Critical-manufacturing and OT security research",
    "desc": "Documented industry incidents, IEC 62443 / NIST SP 800-82"
  },
  "VEC": {
    "name": "Gateway, network and enterprise-infrastructure vector research",
    "desc": "CVEs, OWASP LLM and Agentic Top 10, published research, Five Eyes guidance"
  },
  "SEC": {
    "name": "the enterprise SEC filings",
    "desc": "SEC 10-K (illustrative) risk factors, Item 1C cybersecurity disclosure, MD&A and business sections — the company's own filed language."
  },
  "DOJ": {
    "name": "U.S. Department of Justice and federal courts",
    "desc": "Indictments, guilty pleas, press releases and verdicts in the trade-secret matters."
  },
  "GOV": {
    "name": "U.S. government assessments and rules",
    "desc": "ODNI threat assessment and SEC disclosure requirements."
  },
  "SEMI": {
    "name": "Advanced-manufacturing sector record",
    "desc": "Peer incident disclosures and the SEMI cybersecurity standards."
  },
  "PEER": {
    "name": "Fortune 500 peer benchmarking",
    "desc": "Named programs, org structures, red-team methodology and documented failure patterns."
  },
  "ARCH": {
    "name": "Program strategy architecture",
    "desc": "Published CISO and agency strategy documents, NIST CSF 2.0 profile mechanics, C2M2, FAIR and board-reporting guidance."
  },
  "ATL": {
    "name": "MITRE ATLAS",
    "desc": "Adversarial threat knowledge base for AI systems — case studies, techniques, mitigations."
  },
  "STP": {
    "name": "MITRE Summiting the Pyramid",
    "desc": "Detection robustness scoring and minimum telemetry requirements methodology."
  },
  "SAF": {
    "name": "OpenSSF SAF-MCP",
    "desc": "Technique-to-observation-modality coverage matrix for agent and MCP threats."
  },
  "ARX": {
    "name": "Peer-reviewed and preprint research",
    "desc": "arXiv preprints used for load-bearing technical claims."
  },
  "GTNR": {
    "name": "Gartner research",
    "desc": "Twelve reports supplied by the programme (334 pages). G00859378 supplies the strategy architecture and G00799085 the measurement system; the other ten evidence and refine them. Every marker resolves to a verbatim quote with document ID and page."
  },
  "IND": {
    "name": "Industry research and practitioner sources",
    "desc": "Vendor detection content, deployed-control efficacy reports and published telemetry studies."
  },
  "SNOW": {
    "name": "ServiceNow documentation",
    "desc": "AI Control Tower asset data model and CMDB integration patterns."
  }
};
